// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using guezzer.Data;

namespace guezzer.Data.Migrations
{
    [DbContext(typeof(GuezzerDbContext))]
    [Migration("20181130114944_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("guezzer.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new { Id = new Guid("22661c8e-a8be-48ac-8ec6-d414ee475d26"), Type = "Music" },
                        new { Id = new Guid("f7f6dae5-4ecf-4845-847b-85867d93bd49"), Type = "Funny" },
                        new { Id = new Guid("ecf12e4b-aa6b-4cf9-816b-83922a5912ab"), Type = "Random" }
                    );
                });

            modelBuilder.Entity("guezzer.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("TimesPlayed");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new { Id = new Guid("25ada5e4-2cf7-4102-93a7-77ae4be5f24d"), Name = "BestPlayer", TimesPlayed = 0 },
                        new { Id = new Guid("ddc17a0d-08a9-4ef2-89d5-6f2603cfeec2"), Name = "WorstPlayer", TimesPlayed = 0 }
                    );
                });

            modelBuilder.Entity("guezzer.Entities.Result", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CategoryId");

                    b.Property<Guid?>("PlayerId");

                    b.Property<int>("Score");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("guezzer.Entities.Result", b =>
                {
                    b.HasOne("guezzer.Entities.Category", "Category")
                        .WithMany("Results")
                        .HasForeignKey("CategoryId");

                    b.HasOne("guezzer.Entities.Player", "Player")
                        .WithMany("Results")
                        .HasForeignKey("PlayerId");
                });
#pragma warning restore 612, 618
        }
    }
}
